### PR TITLE
Single-selection mixin

### PR DESCRIPTION
**Pull request by JanMiksovsky**
[Full text of the proposal](https://github.com/elix/rfcs/blob/master/proposals/0002-SingleSelectionMixin.md)

This RFC builds on the initial [functional mixins RFC](https://github.com/elix/rfcs/pull/1). That RFC introduces the general idea of mixins. This RFC introduces a specific mixin for managing single-selection state in components like lists, carousels, combo boxes, etc.

### CODE REVIEW

**Comment by chiefcll** [comment]
👍

**Comment by jouni** [comment]
Should single-selection be an explicit subset of multi-selection? I mean, should we consider defining a multi-selection mixin first, and then reuse that in the single-selection mixin?

The reason I’m asking, is that our team decided to drop direct single-selection APIs from vaadin-grid 2.0, and only have a `selectedItems` property, which the user can then use in a way that makes it seem like a single-select.

I guess user interaction, how the selection is modified by the end user, will be handled by separate mixins in the future (as there can be multiple ways to accomplish that, depending on the selection component)?

**Comment by JanMiksovsky** [comment]
@jouni That’s a great question! I’ve mostly been implementing single-selection components, so between us we should have solid experience to cover many cases.

I've been thinking about single- vs multi-selection for the past two days, but there are many aspects to consider, so it's taking me longer than I thought to organize my thoughts. For now, I just wanted to let you know that I'm working on this, and I'll come back with ideas as soon as I can.

**Comment by jouni** [comment]
I don’t mean to block the merging of this PR, though. I think we can refactor the actual mixin later to be based on a multi-selection mixin, if that seems like a good idea. I think the RFC it self describes single-selection in a good way, and it’s a valid use case for components even without multi-selection.

**Comment by JanMiksovsky** [comment]
Okay, great.

I'll keep working on my thoughts on multi-selection. I do think it'd be good to develop those into a multi-selection mixin as you suggest. Generally, I like letting component development drive mixin development to ensure the mixins actually work in a real-world context. For the single-selection mixin, I'm trying to work towards the creation of an Elix list box component and a tab component.

Following that model, we could defer an actual proposal for a multi-selection mixin to the point when someone wants to tackle the first component that requires it.

**Comment by jouni** [comment]
Read the RFC through, some more comments:

> “The mixin is designed to track selection of HTMLElement objects. As currently prototyped, the mixin could actually be used to track selection of other objects. Unless it is desirable to preserve that flexibility, however, it will be treated as a non-goal. Note that most other Elix mixins that deal with selection will assume that selectable items are, in fact, HTMLElement instances.”

This feels unfeasible for more complex components with virtual/lazy DOM implementations (such as vaadin-grid, vaadin-combo-box), where the interesting stuff is the data objects that are just represented as HTMLElements. But, I think we can keep it as a non-goal for now, and re-evaluate if we want to support this more explicitly when we have such a use case.

For a date picker, I don’t think this mixin can work at all, though, as there’s no finite set of dates to choose from. Selecting dates probably requires another kind of mixin?

**Comment by JanMiksovsky** [comment]
@jouni Good points. I've added a "non-goal" to exclude support for infinite sets (dates) or lazy-loaded sets. As you suggest, we should re-evaluate when we being to implement virtual/lazy list components.

**Pull request merged**
