### PR TITLE
Functional mixins

### PR DESCRIPTION
**Pull request by JanMiksovsky**
[Full text of the proposal](https://github.com/JanMiksovsky/rfcs/blob/functional-mixins/proposals/0000-functional-mixins.md)

This PR represents a Request For Comments on a proposal offered for consideration by the Elix core team. Please add your thoughts on the proposal as comments on this PR.

If/when this proposal is accepted by the core team, it will be merged into the master branch of this `rfcs` repo. It will then be considered "active". Since this particular RFC does not entail any specific changes to the main `elix` repo, becoming "active" will simply signal adoption of the mixin strategy described in the proposal.

### CODE REVIEW

**Comment by RevillWeb** [comment]
Should a formal method of code documentation be enforced for all mixins (and probably components), something along the lines of JSDoc? This will provide developers with code time documentation and intellisense. Additionally it will make generating detailed API documentation for all mixins and components much easier.

**Comment by JanMiksovsky** [comment]
@RevillWeb Yes, the plan is to use jsDoc. I've noted this in the [Contributing](https://github.com/elix/elix/blob/master/Contributing.md) document.

**Comment by robinglen** [comment]
I think we need to discuss how we test these mixins in isolation. Also on the gold standard there is no real discussion of what should be tested, how and why.

This is something I can help with.

**Comment by robbear** [comment]
@thearegee The prototype [Basic Web Component project](https://github.com/basic-web-components/basic-web-components), which has a similar monorepo structure, has unit tests for its mixins. You might take a look at this just to see the approach we took. 

I think it would be great if you wanted to take the lead on testing proposals/examples including how unit tests would become part of our CI workflow. Definitely feel free to drive forward on this as time is available to you. The earlier we build the testing patterns into the workflow, the more fully it will become part of the project culture. This is a big impact area.

**Comment by robinglen** [comment]
Yea I agree, I just think part of the spec of mixins should contain this information about testing the mixins...

Let me look over the prototype

**Comment by JanMiksovsky** [comment]
@thearegee Great point about testing. There's lots to do be done in regards to planning for testing of the project as a whole, and I'm interested to hear your thoughts. Regarding functional mixins specifically, I think the key points are these:

* Each mixin needs a reasonably complete suite of unit tests to exercise its functionality.
* Mixin unit tests should try to test the mixin in isolation. That is, if possible, test fixtures should try to avoid including other mixins. The ideal will be to have test fixtures apply the mixin to HTMLElement. The unit tests for FooMixin should basically look like:

    class FooMixinElement extends FooMixin(HTMLElement) {
      get foo() { return 'Hello'; }
    }
    const fixture = new FooMixinElement();
    assert.equal(fixture.foo, 'Hello');

In our prototyping, we've sometimes used other mixins in constructing test fixtures as an expediency. I think that should still be permissible to get things going, but over time, it's best to isolate which mixin each test is exercising.
* Components that use the mixins can include tests that exercise the integration of multiple mixins. These should generally test the end-user visible interactions. E.g., if the sample shown in the RFC's [jsBin](http://jsbin.com/wikowa/edit?html,output) were a real component, one of its tests might simulate a click on a child, and then confirm that the `selected` class was ultimately applied to the clicked child. Such tests don't need to exhaustively duplicate everything tested in the mixin unit tests, but confirm that the component's basic functionality works as expected.

If that looks good, I can add it to the RFC. If there are other points you think should be captured, please let me know.

**Comment by JanMiksovsky** [comment]
@thearegee I've added a section on Testing to the RFC along the lines I sketched out above. I hope that looks good. Let me know what you think.

**Comment by chiefcll** [comment]
This is confusing for me - IE11 does not support classes - So regardless we'd need babel as it can't be polyfilled. Should we remove #6.

> A smooth migration from ES5 to ES6+. This architecture should feel correct in a future world in which native ES6+ and web components are everywhere, but also be usable today in older ES5 browsers and with polyfills.

**Comment by JanMiksovsky** [comment]
@chiefcll I think we're going to want to support a variety of usage patterns with regards to ES5/ES6:

1. Devs writing in ES6 and transpiling to ES5. This is the common case today. These people will want to `import` the components or mixins directly from Elix ES6 source files in our packages, then transpile using their preferred tool. That transpiler will probably be Babel most often, but it could also be something like TypeScript, Traceur, etc., assuming they all behave reasonably similar.
2. Devs writing in native ES6 targeting modern browsers only. There are probably lucky souls in this camp already that can afford to ignore IE 11. Their numbers will grow over time as IE 11 dies its slow, multi-year death. At the moment, no browser supports the ES6 `import` statement yet, so everyone has to transpile at least those statements, but Safari Technology Preview already supports `import` behind a flag, and this will probably show up in production browsers in 2017, so we should assume it will become common. [I recently did a web component experiment in Safari Technology Preview using pure ES6, including `import`s, and it was a great dev experience. If nothing else, devs will want to be able to develop that way because it's *much* faster, and you can avoid the uncanny valley of trying to debug using source maps.]
3. Devs doing both #1 and #2. They write server code that, for example, looks at the user agent or runs a loading script to decide whether the browser is capable of using native ES6, and falling back to ES5 otherwise. Probably not many people in this camp yet, but it seems likely to become popular.
4. Devs using regular ES5 for most of their app, and who just want to include an Elix component via a script tag that points to a distribution file we transpiled for them. This will probably be common for a while, then diminish in popularity as the world moves to ES6.

The point in the RFC about ES5/ES6 was trying to reflect this complexity. If you think it would help, I could expand it to include a discussion like the points above.

I think that supporting all of the above is achievable, but am interested in your thoughts.

**Comment by chiefcll** [comment]
I wouldn't want to make the RFC any longer. I would just suggest changing the paragraph a bit to 

> but also be usable today in older ES5 browsers (IE11) using polyfills and a transpiler.

**Comment by robinglen** [comment]
@JanMiksovsky sorry the delay also for missing Monday, its sale time of year so things go mental. 

Thanks for adding that of testing it looks good to me. I suppose we should also think about the test strategy, how and where we run the tests but for for the spec this looks good.

**Comment by JanMiksovsky** [comment]
@chiefcll Good solution, thanks. Fixed.

**Pull request merged**
