### PR TITLE
Elix build and distribution

### PR DESCRIPTION
**Pull request by robbear**
[Full text of the proposal](https://github.com/robbear/rfcs/blob/rb-dist/proposals/0000-build-distribution.md)

This RFC describes the proposed model for distributing Elix web components as a single package of multiple components. This differs from the currently common approach, as exemplified by Polymer elements and other element collections, of distributing multiple packages of individual components.

### CODE REVIEW

**Comment by jouni** [comment]
Feels pretty good overall (the monorepo and only one npm distribution package), but I was looking for a description how the versioning would work and maybe some possible examples how things/version numbers might evolve in the future when mixins/elements get added/updated.

**Comment by jouni** [comment]
Also, I wasn’t sure if it was intentional that you use "elix-element-1" in the directory listings and "ElixElement1" in the client index.html examples.

**Comment by jouni** [comment]
You could also remove the "beta" from beta.webcomponents.org

**Comment by robbear** [comment]
Thanks @jouni. I've added a some text on unified versioning and the opportunities/issues for separating versioning on a per-element basis.

I also fixed the paths you pointed out in the client index.html examples and removed "beta" from webcomponents.org. Thanks again.

**Pull request merged**
